### ISSUE TITLE
UIDatePicker disappears after cell collapsing animation

### ISSUE THREAD

**Issue by nawok** [AaronBratcher/TableViewHelper#1]
Hi, Aaron!  Great helper! How can I hotfix this issue? I'm using static tableview, iOS 8.1.3, and this is the first section consisting of two cells: tappable one and date picker cell below it.

**Comment by AaronBratcher** [comment]
When using the helper, I don't use a static table myself.  If you have a
sample project showing the issue, I can look into it.

**Comment by nawok** [comment]
I've added you as a collaborator. Can you see it? Am I doing it right? I'm a newbie by all means. Thanks for your support.

Oh, I forgot about little instructions. Tap Edit, add any contact, then select it and the very first cell inside.

I've just checked your Tester. I has the same issue but it is much less noticeable, because your second section doesn't have a title and has enough items to cover the whole date picker cell while sliding up.

**Comment by AaronBratcher** [comment]
I don't see any issue when using an iPhone 6 simulator. Can you take a few screenshots and email privately to me?

**Comment by nawok** [comment]
**Quick Fix** for everyone interested: change withRowAnimation to .Fade in showCell and hideCell implementations.
