### ISSUE TITLE
Passing data to cell

### ISSUE THREAD

**Issue by Jkurbs** [AaronBratcher/TableViewHelper#3]
How do I pass data to a specific cell?? 
Thank you

`func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        return helper.cellForRow(at: indexPath)
    }`

**Comment by AaronBratcher** [comment]
Create an instance of the cell as an appropriate type first, populate it, then return it. Here's an example:

    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
		let transactionCell = helper.cellForRow(at: indexPath) as! TransactionCell
		transactionCell.upcomingTransaction = upcomingTransactions
		transactionCell.recurringTransaction = recurringTransactions
		transactionCell.transactionKey = transactionKeys[(indexPath as NSIndexPath).row]

		return transactionCell
    }
